# Generated by Django 5.2.6 on 2025-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preshu', '0002_contactmessage_experience_project_skill_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
